project:
  type: sdca-theme

website:
  title: "SDCA Research StenoVoice"
  site-url: "https://steno-aarhus.github.io/steno-voice/"
  repo-url: "https://github.com/steno-aarhus/steno-voice"
  navbar:
    pinned: true
    left:
      - text: "Om StenoVoice"
        menu:
          - text: "Om StenoVoice"
            href: "https://steno-aarhus.github.io/steno-voice/about.html"
          - text: "For deltagere"
            href: "https://steno-aarhus.github.io/steno-voice/participants.html"
          - text: "For Researchers"
            href: "https://steno-aarhus.github.io/steno-voice/researchers.html"
          - text: "SOP"
            href: "https://steno-aarhus.github.io/steno-voice/SOP.html"
    tools:
      - icon: github
        href: "https://github.com/steno-aarhus/"
        aria-label: "GitHub icon: Link to SDCA GitHub organization page"
      - icon: globe
        href: directory.qmd
        aria-label: "Globe icon: Link to directory page of other SDCA websites"

format: sdca-theme-html

editor: 
  markdown:
    wrap: 72
    canonical: true
