---
title: "Velkommen til StenoVoice"
---
## Når stemmen bliver et vindue til helbredet

## Formål
StenoVoice er et forskningsprojekt ved Steno Diabetes Center Aarhus, hvor vi undersøger, om stemmen kan bruges som et værktøj til at forudsige komplikationer og holde øje med sygdomsudviklingen ved diabetes – som fx hjertekarsygdomme og nerveskader. Ved hjælp af kunstig intelligens og maskine læring vil vi analysere optagelser fra stemmen fra personer for at finde Vocal Biomarker (karakteristika i stemmen), der afspejler helbredstilstand.

## Hvorfor udviklere vi metoder som benytter stemmen?
Traditionelle statistiske metoder som anvendes i dag til risikovurdering af hjerte-kar-sygdomme baserer sig på statisk information som alder, køn og livsstil, langtidsblodsuker, diabetes varighed, blodtryk mv. Men, kan disse metoder forbedres ved bruge andre dataformer såsom stemmen?. Signaler fra stemmen afspejlet helbred og derfor tror vi på, at man ved hjælp af stemmeoptagelser kan optimere nutidens metoder.
Det er nemt at optage stemmen. Alle har adgang til en smartphone eller computer, hvilket gør det muligt at optage stemmen hvor som helst og når som helst. Derfor, kan man med stemmebaseret løsninger, nemt og sikkert få et indblik i helbredet hvilket åbner for fleksibel og resoruceoptimerende implementering.
Denne teknologi er et skridt i en retning mod sundhed for alle med;
* tidlig sygdomsdiagnostik,
* rettiddig behandling,
* trykkere liv,
* resource optimerende
* skalerbar til den brede befolkning og andre sygdomsgrupper.

## Hvordan deltager man
Deltagelse i StenoVoice-projektet kan ske på to måder:

1. **StenoVoice**:

På *Steno Diabete Center Aarhus, Aarhus Universitetshospital, Palle Juul-Jensens Boulevard 11, Indgang A. 8200 Skejby* har vi alokeret en mutebox, hvori man kan bidrage ved at optage sin stemme.  Man kan deltage når man besøger Steno Diabetes Center Aarhus til ens årssamtale/sammedagsscreening. Man skal henvende sig til en medarbejder ved indgangen for at blive sat i gang. Selve deltagelse foregår på den måde, at man går ind i en mutebox, besvare et spørgeskemae, laver nogle stemmeøvelser, samt svare på nogle spørgsmål ved at indtale sit svar med stemmen.
Information fra spørgeskemaet, sammedagsscreening og de danske registere sammen med stemmeoptagelserne danner fundamentet for udviklingen af Vocal Biomarker.

Denne video vil gennemgå deltagelsen i projektet:  
[Video-link]

2. **StenoVoice Helbred Midt**: 

Vi invitere personer fra Helbred Midt Kohorten til at deltage ved et online spørgeskema. Personerne vil modtage en invitation i E-boks hvor de vil blive bedt om at besvare et spørgeskema og optage stemmen "hjemmefra".
Information fra spørgeskemaet og de danske registere sammen med stemmeoptagelserne danner fundamentet for udviklingen af Vocal Biomarker i dette projekt.

Denne video vil gennemgå deltagelsen i projektet:  
[Video-link]

## Fremtidsperspektiver
I fremtiden håber vi, at teknologier som StenoVoice kan anvendes bredt i klinisk praksis som en del af regelmæssig sundhedstjek. Vi ser også potentiale i at udvide til at inkludere andre sygdomme og sundhedsproblemer, hvor vokale biomarkører kan spille en rolle i tidlig diagnogstik og risikovurdering.

## Projektledelse

**PI: Adam Hulman, Associate Professor**
adahul@rm.dk

**Projektansvarlig og PhD student: Manuel Thomasen**
manuth@rm.dk / manuth@ph.au.dk

