---
title: StenoVoice Research Overview
description: If you want to know more about our research
---

The StenoVoice project is an interdisciplinary initiative aiming to develop and validate vocal biomarkers for the risk assessment of diabetes-related complications. By integrating deep learning methods with multimodal data, including voice, we aim to provide novel tools for predicting and monitoring cardiovascular disease (CVD), neuropathy, and diabetes distress in people with diabetes. Our research spans methodological innovation, clinical application, and collaboration across international partners.

## Research Objectives

### Study 1: Vocal Biomarkers for Cardiovascular Disease
This study focuses on:

- Initiating voice data collection nested in an existing population-based cohort, i.e., Health in Central Denmark (HICD), and to identify and validate vocal biomarkers for CVD in the general population.

### Study 2: Vocal Biomarkers for Diabetic Neuropathy
This study seeks to:

- Identify vocal biomarkers of neuropathy in people with type 1 diabetes (T1D) and type 2 diabetes (T2D). 

### Study 3: Multimodal Assessment of Diabetes Distress
This study aims to:

- Develop a multimodal approach to detect diabetes distress based on voice recordings and audio transcriptions by people with T1D and T2D.

## Methodology

- **Modeling:** We apply both classical machine learning methods and deep learning architectures to develop and evaluate vocal biomarkers. Our approach includes extracting handcrafted acoustic features from the audio signal and generating deep neural network–based embeddings. These representations serve as inputs to a diverse set of predictive models to assess their performance in identifying relevant vocal markers. In parallel, we fine-tune the underlying neural networks to examine whether task-specific adaptation improves predictive accuracy.
- **Performance Metric:** We will look at discrimination and calibration as our primary performance metrics to compare the different vocal biomarkers. We will use internal validation to do so, since we only have this one Danish-speaking dataset available. In future work, we might validate the best-performing model on an external Danish-based dataset, if it becomes available.

## Collaborations

The project is conducted in collaboration with:

- **Luxembourg Institute of Health**, with the involvement of Guy Fagherazzi, Director of the Department of Precision Health & Head of the "Deep Digital Phenotyping" Research Unit
- **Steno Diabetes Center Copenhagen**, with the involvement of Christian Stevns Hansen
- **Aarhus University**, with the involvement of Stefan Rahr Wagner, Associate Professor at the Department of Electrical and Computer Engineering, Biomedical Engineering & student developers.

## Preliminary Work and Feasibility

- Updated continuously

## Research Team

- **Principal Investigator:** Adam Hulman, Associate Professor at the Department of Public Health, Aarhus University & Senior Data Scientist at Steno Diabetes Center Aarhus
- **PhD Student:** Manuel Thomasen, Steno Diabetes Center Aarhus & Department of Public Health, Aarhus University

- **Affiliated Lab:** Machine Learning and Clinical Prediction [**HulmanLab**](hulmanlab.org), Steno Diabetes Center Aarhus.

## Publications and Resources

- Preprint manuscripts will be available on medRxiv/arXiv.
- Code will be shared via GitHub.
<!--
- [Add links to relevant previous publications by team members.]
-->

## Contact

For questions or collaboration opportunities, please contact:

**Adam Hulman, Associate Professor**  
[adahul@rm.dk](mailto:adahul@rm.dk)

**Manuel Thomasen**  
[manuth@rm.dk](mailto:manuth@rm.dk) / [manuth@ph.au.dk](mailto:manuth@ph.au.dk)  

We welcome researchers interested in digital health, vocal biomarkers, and diabetes epidemiology to reach out for collaboration or discussion.

## Supported by:
This work was supported by a research grant from the Danish Diabetes and Endocrine Academy, funded by the Novo Nordisk Foundation **(NNF22SA0079901)**, and the Danish Data Science Academy, funded by the Novo Nordisk Foundation **(NNF21SA0069429)**, and by Steno Diabetes Center Aarhus which is partly funded by a donation from the Novo Nordisk Foundation **(NNF17SA0031230)**, and by a Data Science Emerging Investigator grant **(NNF22OC0076725)** by the Novo Nordisk Foundation, and funds by Aarhus University, Department of Public Health.
